### ISSUE TITLE
v1.28.0 appears to add extraneous files linked to local configuration

### ISSUE THREAD

**Issue by dnmcgoy** [aws/aws-toolkit-vscode#1932]
**Describe the bug**

Upon upgrading to v1.28.0, when opening VS Code, files that appear to be symlink in nature appear to be added to the current directory.

The format of the extraneous references is:
/Users/computer_user_name/code_location/frontend/file:/Users/computer_user_name/Library/Application Support/Code/User/globalStorage/amazonwebservices.aws-toolkit-vscode

**To Reproduce**
Upgrade to v1.28.0
Open VsCode in any directory

**Expected behavior**

Extraneous files should not be added in the current directory.

-   OS: OSX Catalina 10.15.7
-   Visual Studio Code Version: 1.59.0
-   AWS Toolkit Version: 1.28.0

**Comment by tigerinus** [comment]
Same issue here. I see

```bash
$ realpath file\:/home/opc/.vscode-server/data/User/globalStorage/amazonwebservices.aws-toolkit-vscode/
/home/opc/file:/home/opc/.vscode-server/data/User/globalStorage/amazonwebservices.aws-toolkit-vscode
```

**Comment by JadenSimon** [comment]
I'm currently unable to reproduce this with the same OS, VS Code, and Toolkit version. Are either of you using remote development by chance? I'm not sure if that would have anything to do with it but trying to rule out possible differences.

**Comment by tigerinus** [comment]
> I'm currently unable to reproduce this with the same OS, VS Code, and Toolkit version. Are either of you using remote development by chance? I'm not sure if that would have anything to do with it but trying to rule out possible differences.
> 
> Any other settings or differences in environment that y'all can think of would be very helpful.

Yes - VSCode for Windows, remoted to Linux in the cloud.

**Comment by JadenSimon** [comment]
Good to know. This is probably an oversight on our end in regards to path normalization for a new feature, with remote development being an edge-case.

**Comment by markpendlebury** [comment]
Same here. I'm currently working on a dotnet core application and noticed a folder named "file:" in my applications root directory. This application has nothing to do with aws, disabling the aws plugin for vscode stopped this behaviour.

To Confirm: 
With the AWS extension enabled. If I delete the folder named "File:" and restart vscode the folder is created again. 
If i repeat the process with the AWS extension disabled the folder doesn't appear.

Environment Details: 

- VSCode Version: 1.59.0
- OS: Pop!_OS (21.04) (Based on Ubuntu 21.04)
- Extension version: 1.28.0

**Comment by dnmcgoy** [comment]
> I'm currently unable to reproduce this with the same OS, VS Code, and Toolkit version. Are either of you using remote development by chance? I'm not sure if that would have anything to do with it but trying to rule out possible differences.
> 
> Any other settings or differences in environment that y'all can think of would be very helpful.

I don't believe we have any remote development config enabled.  Can you let us know how we can confirm?

**Comment by markpendlebury** [comment]
> I'm currently unable to reproduce this with the same OS, VS Code, and Toolkit version. Are either of you using remote development by chance? I'm not sure if that would have anything to do with it but trying to rule out possible differences.
> 
> Any other settings or differences in environment that y'all can think of would be very helpful.

This happened to me with a fresh (synced) installation of vscode. I haven't used the AWS plugin yet therefore had no aws configuration profiles set (access keys/secrets etc) therefore no remote deployment settings are configured either.

**Comment by JadenSimon** [comment]
> I don't believe we have any remote development config enabled. Can you let us know how we can confirm?

I believe the statusbar would show some text (SSH/WSL/Dev Container) in the bottom left of VS Code, but if you aren't sure then you probably are not using remote development.

> This happened to me with a fresh (synced) installation of vscode. I haven't used the AWS plugin yet therefore had no aws configuration profiles set (access keys/secrets etc) therefore no remote deployment settings are configured either.

So remote development probably isn't the issue.

> This seems to be created by the toolkit logs

Logs were moved to `globalStorage` in #1694, since this is happening only in the latest release I don't think that's the cause. But it does seem that _something_ we're creating in the VSC global storage is causing this. 

> possibly related to the vscode trust settings?

Maybe. I'll test some different theories with this bug and report back.

**Comment by JadenSimon** [comment]
I have a PR out with a potential fix. If anyone has the chance to try out this test VSIX that'd be great!

Instructions:
1. Download and extract [buildArtifacts.zip](https://github.com/aws/aws-toolkit-vscode/files/6969916/buildArtifacts.zip)
2. From the VSCode command list (ctrl-shift-p or cmd-shift-p) run Extensions: Install from VSIX... to install the *.vsix file.
3. Reload VSCode and verify that the Toolkit has version 1.29-6b9e6af67c60

**Comment by jkemp814** [comment]
Same issue under MX Linux (Debian 10 based)

Hello, When connecting to the AWS services through the extension, I noticed a folder name 'file:' with many subdirectories in my home folder. 

Shouldn't this be under .config folder? It does find the .aws folder for my config and credentials. 

This is the structure that is being created. file:/home/ ' user name'/ .config/Code/User/globalStorage/ amazonwebservices.aws-toolkit-vscode/ (two JSON files)

**Comment by justinmk3** [comment]
@jkemp814 it is a bug which is fixed but the fix is not yet released. See https://github.com/aws/aws-toolkit-vscode/issues/1932#issuecomment-896973022 to try the development version which fixes this issue.

**Comment by merlinblack** [comment]
I get the same issue - except the folder tree is showing up in my project directories. I usually start VScode from a terminal in the project directory with
```
code .
```
If that makes any difference. I guess it's missing slashes in the name.

**Comment by justinmk3** [comment]
Fixed in AWS Toolkit 1.29

**Comment by mouimet-infinisoft** [comment]
Hi folks, Just to let you know that problem still persisting with following configuration.
I solved it with by removing extension 1.34.0 and installing  @JadenSimon  VSIX artefact

Error message
'aws.login not found'

ENVIRONMENT
Aws toolkit: 1.34.0

VSCode
Version: 1.62.3 (user setup)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:11:14.551Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by justinmk3** [comment]
> 'aws.login not found'

@mouimet-infinisoft that doesn't look related to this issue. Did you mean to comment on #2331 ?
