### ISSUE TITLE
Rerun credential_process when expired instead of failing

### ISSUE THREAD

**Issue by thomasfinstad** [aws/aws-toolkit-vscode#2664]
## Problem

We have temporary creds lasting only 1 hour, when they expire toolkit does not rerun the credential_process when it notices the creds have expired, instead it just says they are expired and fails.

## Steps to reproduce the issue

- Profile with external credential_process to fetch the credentials
- Wait until expire time elapses

## Expected behavior

When toolkit tries to fetch info from aws and notices the creds are expired it should re-run the credential_process to refresh creds.

## System details (run the `AWS: About Toolkit` command)

- OS:  Darwin arm64 21.5.0
- Visual Studio Code Extension Host Version:  1.67.2
- AWS Toolkit Version:  1.38.0

**Comment by JadenSimon** [comment]
Thanks for the report!

This may be a caching issue and https://github.com/aws/aws-toolkit-vscode/pull/2618 should fix this problem.

**Comment by justinmk3** [comment]
AWS Toolkit 1.39 includes https://github.com/aws/aws-toolkit-vscode/pull/2618 . Please try it and let us know.

**Comment by thomasfinstad** [comment]
**The issue still persists.**

OS: Darwin arm64 21.5.0
Visual Studio Code extension host:  1.67.2
AWS Toolkit:  1.39.0
node: 16.13.0
electron: 17.4.1


Here is the log:
```
2022-06-12 14:02:41 [ERROR]: [ExpiredToken: The provided token has expired.
	at constructor.extractError (/Users/REDACTED/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.39.0/dist/src/main.js:9:10340)
	at constructor.callListeners (/Users/REDACTED/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.39.0/dist/src/main.js:7:21079)
	at constructor.emit (/Users/REDACTED/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.39.0/dist/src/main.js:7:20788)
	at constructor.emitEvent (/Users/REDACTED/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.39.0/dist/src/main.js:7:6641)
	at constructor.e (/Users/REDACTED/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.39.0/dist/src/main.js:7:2227)
	at G.runTo (/Users/REDACTED/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.39.0/dist/src/main.js:19:1767)
	at /Users/REDACTED/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.39.0/dist/src/main.js:19:1979
	at constructor.<anonymous> (/Users/REDACTED/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.39.0/dist/src/main.js:7:2438)
	at constructor.<anonymous> (/Users/REDACTED/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.39.0/dist/src/main.js:7:6696)
	at constructor.callListeners (/Users/REDACTED/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.39.0/dist/src/main.js:7:21183)
	at constructor.emit (/Users/REDACTED/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.39.0/dist/src/main.js:7:20788)
	at constructor.emitEvent (/Users/REDACTED/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.39.0/dist/src/main.js:7:6641)
	at constructor.e (/Users/REDACTED/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.39.0/dist/src/main.js:7:2227)
	at G.runTo (/Users/REDACTED/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.39.0/dist/src/main.js:19:1767)
	at /Users/REDACTED/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.39.0/dist/src/main.js:19:1979
	at constructor.<anonymous> (/Users/REDACTED/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.39.0/dist/src/main.js:7:2438)
	at constructor.<anonymous> (/Users/REDACTED/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.39.0/dist/src/main.js:7:6696)
	at constructor.callListeners (/Users/REDACTED/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.39.0/dist/src/main.js:7:21183)
	at e (/Users/REDACTED/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.39.0/dist/src/main.js:7:20964)
	at IncomingMessage.<anonymous> (/Users/REDACTED/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.39.0/dist/src/main.js:2:223305)
	at IncomingMessage.emit (node:events:402:35)
	at IncomingMessage.emit (node:domain:475:12)
	at endReadableNT (node:internal/streams/readable:1343:12)
	at processTicksAndRejections (node:internal/process/task_queues:83:21)] {
  code: 'ExpiredToken',
  region: null,
  time: 2022-06-12T12:02:41.162Z,
  requestId: 'REDACTED',
  extendedRequestId: 'REDACTED',
  cfId: undefined,
  statusCode: 400,
  retryable: true
}
```

**Comment by JadenSimon** [comment]
@thomasfinstad 

Can you double-check that whatever you're using for `credential_process` follows the spec outline in https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html ?

A missing or invalid `Expiration` may cause the AWS SDK to assume that the credentials never expire. And so the request just fails instead of calling back into the Toolkit.

**Comment by thomasfinstad** [comment]
This is the response I get when running it manually just now. From what I understand it follows the spec you outline.

```
{
	"Version": 1,
	"AccessKeyId": "REDACTED",
	"SecretAccessKey": "REDACTED",
	"SessionToken": "REDACTED",
	"Expiration": "2022-06-14T18:26:15+00:00"
}
```

**Comment by JadenSimon** [comment]
Yeah that looks correct to me, though I noticed that the tools I'm using outputs the simplified ISO format: `2022-06-14T18:26:15Z`

I'm wondering if the AWS JS SDK fails on the extended format for some reason. The other possibility is that credentials are being written to a profile with the same name in `~/.aws/credentials` as some sort of compatibility mechanism. I'd make sure that your profile isn't being merged with static credentials somewhere. Otherwise the static credentials override the refresh attempt.

**Comment by thomasfinstad** [comment]
There is nothing in the credentials file for the profile I pick in VSCode, I made the profile only for this usecase.

I have now changed the output to follow the same time format as you:
```
{
	"Version": 1,
	"AccessKeyId": "...",
	"SecretAccessKey": "...",
	"SessionToken": "...",
	"Expiration": "2022-06-21T10:22:35Z"
}
```

But the same issue persists, a few hours later:

```
2022-06-21 14:35:51 [ERROR]: [ExpiredTokenException: The security token included in the request is expired
	at constructor.S (/Users/USER/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.40.0/dist/src/main.js:6:7865)
	at constructor.callListeners (/Users/USER/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.40.0/dist/src/main.js:7:21079)
	at constructor.emit (/Users/USER/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.40.0/dist/src/main.js:7:20788)
	at constructor.emitEvent (/Users/USER/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.40.0/dist/src/main.js:7:6641)
	at constructor.e (/Users/USER/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.40.0/dist/src/main.js:7:2227)
	at G.runTo (/Users/USER/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.40.0/dist/src/main.js:19:1767)
	at /Users/USER/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.40.0/dist/src/main.js:19:1979
	at constructor.<anonymous> (/Users/USER/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.40.0/dist/src/main.js:7:2438)
	at constructor.<anonymous> (/Users/USER/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.40.0/dist/src/main.js:7:6696)
	at constructor.callListeners (/Users/USER/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.40.0/dist/src/main.js:7:21183)
	at constructor.emit (/Users/USER/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.40.0/dist/src/main.js:7:20788)
	at constructor.emitEvent (/Users/USER/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.40.0/dist/src/main.js:7:6641)
	at constructor.e (/Users/USER/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.40.0/dist/src/main.js:7:2227)
	at G.runTo (/Users/USER/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.40.0/dist/src/main.js:19:1767)
	at /Users/USER/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.40.0/dist/src/main.js:19:1979
	at constructor.<anonymous> (/Users/USER/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.40.0/dist/src/main.js:7:2438)
	at constructor.<anonymous> (/Users/USER/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.40.0/dist/src/main.js:7:6696)
	at constructor.callListeners (/Users/USER/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.40.0/dist/src/main.js:7:21183)
	at e (/Users/USER/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.40.0/dist/src/main.js:7:20964)
	at IncomingMessage.<anonymous> (/Users/USER/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.40.0/dist/src/main.js:2:223305)
	at IncomingMessage.emit (node:events:402:35)
	at IncomingMessage.emit (node:domain:475:12)
	at endReadableNT (node:internal/streams/readable:1343:12)
	at processTicksAndRejections (node:internal/process/task_queues:83:21)] {
  code: 'ExpiredTokenException',
  time: 2022-06-21T12:35:51.340Z,
  requestId: '91f55cfd-f3ee-4fb4-a76c-5654dba98b8e',
  statusCode: 400,
  retryable: true
}
```

**Comment by justinmk3** [comment]
AWS Toolkit 1.41 includes https://github.com/aws/aws-toolkit-vscode/pull/2712 which should fix this issue.

**Comment by RuyOliveira-ZH** [comment]
I'm still facing this same issue with AWS CLI version 2.13.5 running in Macos.

**Comment by justinmk3** [comment]
@RuyOliveira-ZH AWS CLI is not part of (nor used by) AWS Toolkit, are you looking for https://github.com/aws/aws-cli
