### ISSUE TITLE
`GLIBCXX_3.4.29' not found

### ISSUE THREAD

**Issue by fann95** [aws/aws-toolkit-vscode#8353]
## Problem

[Error - 7:56:48 PM] Server initialization failed.
  Message: Request initialize failed with message: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/stas/.cache/aws/toolkits/language-servers/cloudformation-languageserver/1.1.0/cloudformation-languageserver-1.1.0-linux-x64-node22/node_modules/tree-sitter/prebuilds/linux-x64/tree-sitter.node)
  Code: -32603 
[Error - 7:56:48 PM] AWS CloudFormation client: couldn't create connection to server.
  Message: Request initialize failed with message: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/stas/.cache/aws/toolkits/language-servers/cloudformation-languageserver/1.1.0/cloudformation-languageserver-1.1.0-linux-x64-node22/node_modules/tree-sitter/prebuilds/linux-x64/tree-sitter.node)
  Code: -32603 
[07:56:48 PM] INFO: [Init] AWS CloudFormation initializing...
    ClientInfo: {
      "name": "Cursor",
      "version": "1.105.1"
    }
    NodeEnv: "production"
    AwsEnv: "prod"
    aws: {
      "clientInfo": {
        "extension": {
          "name": "amazonwebservices.cloudformation",
          "version": "1.0.0"
        },
        "clientId": "73375e01-f8e0-48da-b3ca-5d77b05d0319"
      },
      "telemetryEnabled": true
    }
[07:56:48 PM] INFO: [Init] 
    Machine: "linux-x64"
    Process: "linux-x64"
    Runtime: "node=22.20.0 v8=13.8.258.32-electron.0 uv=1.51.0 modules=136"
[07:56:48 PM] INFO: [TelemetryService] Telemetry enabled for 73375e01-f8e0-48da-b3ca-5d77b05d0319

**Comment by satyakigh** [comment]
Was Cursor installed via Snap store or other equivalent stores? Can you please provide your machine specs, Linux kernel version, etc. 

Thanks

**Comment by Subhranil780** [comment]
cannot reproduce

**Comment by ybob1980** [comment]
I'm facing the similar issue and the latest version works for me is 3.84. It seems 3.84 still use cfn-lint from the other place. Newer version has cfn-lint embedded which has node runtime required GLIBCXX_3.4. GLIBCXX_3.4 doesn't available in Amazon AL2. Will you have any fix for it?

**Comment by fromthewoods** [comment]
I am seeing this issue as well. Q's analysis:

# CloudFormation Language Server fails to initialize: GLIBCXX_3.4.29 not found

## Summary
The CloudFormation language server in AWS Toolkit fails to start due to a GLIBC version compatibility issue with the bundled tree-sitter binary.

## Environment
- **AWS Toolkit Version**: 3.89.0 (2025-11-25)
- **VSCode Version**: 1.105.1
- **Node Version**: 22.19.0
- **OS**: Amazon Linux 2 (5.10.245-243.979.amzn2int.x86_64)
- **System libstdc++**: Up to GLIBCXX_3.4.24
- **VSCode sysroot libstdc++**: Up to GLIBCXX_3.4.25

## Error Message
```
[Error - 4:33:40 PM] Server initialization failed.
Message: Request initialize failed with message: /opt/vsc-sysroot/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /local/home/<username>/.cache/aws/toolkits/language-servers/cloudformation-languageserver/1.1.0/cloudformation-languageserver-1.1.0-linux-x64-node22/node_modules/tree-sitter/prebuilds/linux-x64/tree-sitter.node)
Code: -32603
```

## Root Cause
The `tree-sitter.node` binary in the CloudFormation language server was compiled against a newer version of libstdc++ (requiring GLIBCXX_3.4.29) than what's available in most Linux environments, including Amazon Linux 2 and VSCode's bundled sysroot.

## Reproduction Steps
1. Install AWS Toolkit 3.85.0 (or higher) on Amazon Linux 2 or similar environment
2. Open a CloudFormation file (.yaml/.json)
3. Check VSCode logs: `~/.vscode-server/data/logs/[DATE]/exthost*/output_logging*/AWS CloudFormation.log`

## Impact
- CloudFormation language features completely unavailable
- No syntax highlighting, validation, or IntelliSense for CloudFormation templates
- Issue is persistent across toolkit updates and cache clears

## Attempted Solutions
- ✅ Cleared language server cache (`rm -rf ~/.cache/aws/toolkits/language-servers/cloudformation-languageserver`)
- ✅ Updated to latest AWS Toolkit version
- ❌ System libstdc++ updates (Amazon Linux 2 max: GLIBCXX_3.4.24)
- ❌ LD_LIBRARY_PATH workarounds (cause segmentation faults)

## Current Workaround
- Roll back to AWS Toolkt 3.84.0

**Comment by satyakigh** [comment]
We are working towards fixing this issue for AL2s, AL2 uses a old linux kernel which doesn't have the GLIBCXX version tree sitter requires. 

We also found this issue for new linux kernels where VSCode/Cursor/etc. was installed via the Ubuntu software store or other stores - this causes VSCode to run in a sandbox mode which has an older linux kernel.

This issue only impacts the new CloudFormation features launched in ToolKit 3.85.0

**Comment by satyakigh** [comment]
We have released a new version of AWS ToolKit and AWS CloudFormation LanguageServer which fixes this problem, please update the extension and restart VSCode to get the latest changes.

**Comment by ybob1980** [comment]
It seems still not work in AL2 as it only have glibc 2.26.

```
> ldd --version
ldd (GNU libc) 2.26
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

I got the following error

```
[Error - 9:45:56 PM] AWS CloudFormation client: couldn't create connection to server.
  Message: Request initialize failed with message: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by ~/.cache/aws/toolkits/language-servers/cloudformation-languageserver/1.2.0/cloudformation-languageserver-1.2.0-linuxglib2.28-x64-node18/node_modules/lmdb/build/Release/lmdb.node)
  Code: -32603 
```

**Comment by fromthewoods** [comment]
Worked for me on AL2! Was able to set up authentication and see stacks in my account. Thanks!

**Comment by ybob1980** [comment]
Do you have glibc 2.28 in your AL2?

**Comment by fromthewoods** [comment]
I have 2.26 on my AL2 machine:
```
% ldd --version
ldd (GNU libc) 2.26
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```
On my AL2 machine
- In vscode the `AWS Toolkit Logs` show no errors and the extension seems to work (I can authenticate to AWS accounts and see CFN stacks).
- In Kiro IDE (vscode variant) I get the following error:

```
2026-01-06 14:48:16.991 [error] [D [Error]: CloudFormation language server failed to start
	at D.chain (/local/home/<user>/.kiro-server/extensions/amazonwebservices.aws-toolkit-vscode-3.91.0-universal/dist/src/extensionNode.js:4037:43)
	at ot (/local/home/<user>/.kiro-server/extensions/amazonwebservices.aws-toolkit-vscode-3.91.0-universal/dist/src/extensionNode.js:2891:19691)] {
  code: undefined,
  details: undefined,
  cause: [u [Error]: Request initialize failed with message: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /local/home/<user>/.cache/aws/toolkits/language-servers/cloudformation-languageserver/1.2.0/cloudformation-languageserver-1.2.0-linuxglib2.28-x64-node18/node_modules/lmdb/build/Release/lmdb.node)
  	at hr (/local/home/<user>/.kiro-server/extensions/amazonwebservices.aws-toolkit-vscode-3.91.0-universal/dist/src/extensionNode.js:1465:248)
  	at Tr (/local/home/<user>/.kiro-server/extensions/amazonwebservices.aws-toolkit-vscode-3.91.0-universal/dist/src/extensionNode.js:1464:16525)
  	at wt (/local/home/<user>/.kiro-server/extensions/amazonwebservices.aws-toolkit-vscode-3.91.0-universal/dist/src/extensionNode.js:1464:16661)
  	at Immediate.<anonymous> (/local/home/<user>/.kiro-server/extensions/amazonwebservices.aws-toolkit-vscode-3.91.0-universal/dist/src/extensionNode.js:1464:16409)
  	at process.processImmediate (node:internal/timers:485:21)
  	at process.topLevelDomainCallback (node:domain:161:15)
  	at process.callbackTrampoline (node:internal/async_hooks:128:24)] {
    code: -32603,
    data: undefined
  }
}
```

**Comment by ybob1980** [comment]
yes. I forgot to mention. I also use kiro. I recall vscode made some effort to support AL2. Is it related?

**Comment by fromthewoods** [comment]
That is likely.

**Comment by satyakigh** [comment]
Hello, is this issue still happening?
